/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.travels.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.travels.model.Trip;
import com.liferay.travels.model.TripModel;
import com.liferay.travels.model.TripSoap;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Trip service. Represents a row in the &quot;LiferayTravels_Trip&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>TripModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TripImpl}.
 * </p>
 *
 * @author Javier de Arcos
 * @see TripImpl
 * @generated
 */
@JSON(strict = true)
public class TripModelImpl extends BaseModelImpl<Trip> implements TripModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a trip model instance should use the <code>Trip</code> interface instead.
	 */
	public static final String TABLE_NAME = "LiferayTravels_Trip";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"tripId", Types.BIGINT},
		{"name", Types.VARCHAR}, {"description", Types.VARCHAR},
		{"startingDate", Types.TIMESTAMP}, {"image", Types.VARCHAR},
		{"groupId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"companyId", Types.BIGINT},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("tripId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("description", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("startingDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("image", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table LiferayTravels_Trip (uuid_ VARCHAR(75) null,tripId LONG not null primary key,name VARCHAR(75) null,description VARCHAR(75) null,startingDate DATE null,image TEXT null,groupId LONG,userId LONG,userName VARCHAR(75) null,companyId LONG,createDate DATE null,modifiedDate DATE null)";

	public static final String TABLE_SQL_DROP =
		"drop table LiferayTravels_Trip";

	public static final String ORDER_BY_JPQL =
		" ORDER BY trip.startingDate ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY LiferayTravels_Trip.startingDate ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	public static final long GROUPID_COLUMN_BITMASK = 2L;

	public static final long UUID_COLUMN_BITMASK = 4L;

	public static final long STARTINGDATE_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static Trip toModel(TripSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Trip model = new TripImpl();

		model.setUuid(soapModel.getUuid());
		model.setTripId(soapModel.getTripId());
		model.setName(soapModel.getName());
		model.setDescription(soapModel.getDescription());
		model.setStartingDate(soapModel.getStartingDate());
		model.setImage(soapModel.getImage());
		model.setGroupId(soapModel.getGroupId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCompanyId(soapModel.getCompanyId());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static List<Trip> toModels(TripSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<Trip> models = new ArrayList<Trip>(soapModels.length);

		for (TripSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public TripModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _tripId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setTripId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _tripId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Trip.class;
	}

	@Override
	public String getModelClassName() {
		return Trip.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Trip, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Trip, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Trip, Object> attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Trip)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Trip, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Trip, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept((Trip)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Trip, Object>> getAttributeGetterFunctions() {
		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Trip, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, Trip>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			Trip.class.getClassLoader(), Trip.class, ModelWrapper.class);

		try {
			Constructor<Trip> constructor =
				(Constructor<Trip>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<Trip, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<Trip, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<Trip, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<Trip, Object>>();
		Map<String, BiConsumer<Trip, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<Trip, ?>>();

		attributeGetterFunctions.put("uuid", Trip::getUuid);
		attributeSetterBiConsumers.put(
			"uuid", (BiConsumer<Trip, String>)Trip::setUuid);
		attributeGetterFunctions.put("tripId", Trip::getTripId);
		attributeSetterBiConsumers.put(
			"tripId", (BiConsumer<Trip, Long>)Trip::setTripId);
		attributeGetterFunctions.put("name", Trip::getName);
		attributeSetterBiConsumers.put(
			"name", (BiConsumer<Trip, String>)Trip::setName);
		attributeGetterFunctions.put("description", Trip::getDescription);
		attributeSetterBiConsumers.put(
			"description", (BiConsumer<Trip, String>)Trip::setDescription);
		attributeGetterFunctions.put("startingDate", Trip::getStartingDate);
		attributeSetterBiConsumers.put(
			"startingDate", (BiConsumer<Trip, Date>)Trip::setStartingDate);
		attributeGetterFunctions.put("image", Trip::getImage);
		attributeSetterBiConsumers.put(
			"image", (BiConsumer<Trip, String>)Trip::setImage);
		attributeGetterFunctions.put("groupId", Trip::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId", (BiConsumer<Trip, Long>)Trip::setGroupId);
		attributeGetterFunctions.put("userId", Trip::getUserId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<Trip, Long>)Trip::setUserId);
		attributeGetterFunctions.put("userName", Trip::getUserName);
		attributeSetterBiConsumers.put(
			"userName", (BiConsumer<Trip, String>)Trip::setUserName);
		attributeGetterFunctions.put("companyId", Trip::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId", (BiConsumer<Trip, Long>)Trip::setCompanyId);
		attributeGetterFunctions.put("createDate", Trip::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate", (BiConsumer<Trip, Date>)Trip::setCreateDate);
		attributeGetterFunctions.put("modifiedDate", Trip::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate", (BiConsumer<Trip, Date>)Trip::setModifiedDate);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		_columnBitmask |= UUID_COLUMN_BITMASK;

		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getTripId() {
		return _tripId;
	}

	@Override
	public void setTripId(long tripId) {
		_tripId = tripId;
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_name = name;
	}

	@JSON
	@Override
	public String getDescription() {
		if (_description == null) {
			return "";
		}
		else {
			return _description;
		}
	}

	@Override
	public void setDescription(String description) {
		_description = description;
	}

	@JSON
	@Override
	public Date getStartingDate() {
		return _startingDate;
	}

	@Override
	public void setStartingDate(Date startingDate) {
		_columnBitmask = -1L;

		_startingDate = startingDate;
	}

	@JSON
	@Override
	public String getImage() {
		if (_image == null) {
			return "";
		}
		else {
			return _image;
		}
	}

	@Override
	public void setImage(String image) {
		_image = image;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(Trip.class.getName()));
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), Trip.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Trip toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Trip>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		TripImpl tripImpl = new TripImpl();

		tripImpl.setUuid(getUuid());
		tripImpl.setTripId(getTripId());
		tripImpl.setName(getName());
		tripImpl.setDescription(getDescription());
		tripImpl.setStartingDate(getStartingDate());
		tripImpl.setImage(getImage());
		tripImpl.setGroupId(getGroupId());
		tripImpl.setUserId(getUserId());
		tripImpl.setUserName(getUserName());
		tripImpl.setCompanyId(getCompanyId());
		tripImpl.setCreateDate(getCreateDate());
		tripImpl.setModifiedDate(getModifiedDate());

		tripImpl.resetOriginalValues();

		return tripImpl;
	}

	@Override
	public int compareTo(Trip trip) {
		int value = 0;

		value = DateUtil.compareTo(getStartingDate(), trip.getStartingDate());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Trip)) {
			return false;
		}

		Trip trip = (Trip)object;

		long primaryKey = trip.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		TripModelImpl tripModelImpl = this;

		tripModelImpl._originalUuid = tripModelImpl._uuid;

		tripModelImpl._originalGroupId = tripModelImpl._groupId;

		tripModelImpl._setOriginalGroupId = false;

		tripModelImpl._originalCompanyId = tripModelImpl._companyId;

		tripModelImpl._setOriginalCompanyId = false;

		tripModelImpl._setModifiedDate = false;

		tripModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<Trip> toCacheModel() {
		TripCacheModel tripCacheModel = new TripCacheModel();

		tripCacheModel.uuid = getUuid();

		String uuid = tripCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			tripCacheModel.uuid = null;
		}

		tripCacheModel.tripId = getTripId();

		tripCacheModel.name = getName();

		String name = tripCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			tripCacheModel.name = null;
		}

		tripCacheModel.description = getDescription();

		String description = tripCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			tripCacheModel.description = null;
		}

		Date startingDate = getStartingDate();

		if (startingDate != null) {
			tripCacheModel.startingDate = startingDate.getTime();
		}
		else {
			tripCacheModel.startingDate = Long.MIN_VALUE;
		}

		tripCacheModel.image = getImage();

		String image = tripCacheModel.image;

		if ((image != null) && (image.length() == 0)) {
			tripCacheModel.image = null;
		}

		tripCacheModel.groupId = getGroupId();

		tripCacheModel.userId = getUserId();

		tripCacheModel.userName = getUserName();

		String userName = tripCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			tripCacheModel.userName = null;
		}

		tripCacheModel.companyId = getCompanyId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			tripCacheModel.createDate = createDate.getTime();
		}
		else {
			tripCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			tripCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			tripCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		return tripCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Trip, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Trip, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Trip, Object> attributeGetterFunction = entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((Trip)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<Trip, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<Trip, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Trip, Object> attributeGetterFunction = entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((Trip)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Trip>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private String _uuid;
	private String _originalUuid;
	private long _tripId;
	private String _name;
	private String _description;
	private Date _startingDate;
	private String _image;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _userId;
	private String _userName;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _columnBitmask;
	private Trip _escapedModel;

}